spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
        routes:
          - id: clienteService
            uri: lb://client-service
            predicates:
              - Path=/clients/**

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

