server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  #Eureka cannot register itself as a client.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-discovery-service
  config:
    import: optional:configserver:http://localhost:8080